version: '3.8'

services:
  postgres_db:
    container_name: postgres_spb
    restart: unless-stopped
    image: postgres:14
    networks:
      - simple_block_network
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5431:5432
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/api-psql/:/docker-entrypoint-initdb.d/

  api-migration:
    container_name: postgres_spb_migrations
    build:
      context: .
      dockerfile: Dockerfile-Migration
    depends_on:
      - postgres_db
    networks:
      - simple_block_network
    env_file:
      - .env-migration
    environment:
      DB_HOST: postgres_db
      POSTGRES_DB_HOST: postgres_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/api-psql/:/docker-entrypoint-initdb.d/

networks:
  simple_block_network:
    driver: bridge
volumes:
  pgdata:
