export const productCategories = [
  'Áo sơ mi',
  'Áo polo',
  'Áo thun',
  'Áo khoác',
  'Áo nỉ',
  'Áo len',
  'Quần tây',
  'Quần jeans',
  'Quần nỉ',
  'Quần đùi',
  'Quần lót',
  'Quần giữ nhiệt',
  'Tất',
  'Đồ ngủ',
  'Áo choàng tắm',
  'Vest',
  'Áo hai dây & ba lỗ',
  'Áo ống',
  'Áo croptop',
  'Áo liền quần',
  'Áo choàng',
  'Blazer',
  'Khác',
  'Quần legging',
  'Quần váy',
  'Quần âu',
  'Váy',
  'Đồ lót',
  'Bốt thời trang',
  'Bốt đi mưa',
  'Bốt bảo hộ',
  'Giày thể thao/sneaker',
  'Giày sục',
  'Giày tây',
  'Dép xỏ ngón',
  'Xăng đan',
  'Dép đi trong nhà',
  'Dụng cụ chăm sóc vệ sinh giày dép',
  'Khử mùi',
  'Giày bale',
  'Giày lười',
  'Giày sục & giày búp bê',
  'Giày cao gót',
  'Giày đế xuồng',
  'Xăng đan đế bằng',
  'Dép kẹp/dép xỏ ngón',
  'Phụ kiện giày dép',
  'Nhẫn',
  'Bông tai',
  'Khăn choàng',
  'Găng tay',
  'Băng đô tóc',
  'Đồ buộc tóc & nơ',
  'Kẹp tóc',
  'Tóc giả & tóc nối',
  'Đồ cài tóc',
  'Vòng tay & lắc tay',
  'Lắc chân',
  'Mũ',
  'Dây chuyền',
  'Kính mắt',
  'Gọng kính',
  'Hộp kính và phụ kiện',
  'Đồng hồ nữ',
  'Đồng hồ nam',
  'Đồng hồ theo cặp/bộ',
  'Phụ kiện đồng hồ',
  'Đồ dùng du lịch cho bé',
  'Đồ dùng ăn dặm cho bé',
  'Phụ kiện cho mẹ',
  'Chăm sóc sức khỏe mẹ',
  'Đồ dùng phòng tắm',
  'Đồ dùng phòng ngủ',
  'Thiết bị giám sát trẻ',
  'Màn chống muỗi',
  'Bộ đệm cũi, quây cũi & thanh chắn',
  'Bọc góc và cạnh',
  'Thanh chắn cửa & cầu thang',
  'Khóa & dây đai an toàn',
  'Sữa công thức',
  'Cháo, thực phẩm xay nhuyễn',
  'Đồ ăn nhẹ cho bé',
  'Sữa pha sẵn',
  'Bộ lót thay tã',
  'Bô vệ sinh',
  'Tã dùng một lần',
  'Tã vải & phụ kiện',
  'Quần áo bé trai',
  'Quần áo bé gái',
  'Bao tay & tất',
  'Giày bé trai',
  'Giày bé gái',
  'Phụ kiện trẻ em & trẻ sơ sinh',
  'Thiết bị vệ sinh',
  'Thiết bị xử lý không khí',
  'Máy may & phụ kiện',
  'Bàn là',
  'Tivi',
  'Ăng ten tivi',
  'Tivi & đầu thu kĩ thuật số',
  'Giá treo tivi',
  'Máy lọc nước',
  'Ấm siêu tốc',
  'Máy ép, xay sinh tố, làm sữa hạt',
  'Máy pha cà phê & phụ kiện',
  'Máy trộn thực phẩm',
  'Máy rửa bát đĩa',
  'Bếp từ',
  'Nồi chiên ',
  'Lò vi sóng',
  'Lò nướng',
  'Máy nướng bánh',
  'Máy chế biến thực phẩm',
  'Nồi nấu đa năng',
  'Nồi áp suất',
  'Nồi nấu chậm',
  'Nồi cơm điện',
  'Tủ lạnh ',
  'Tủ đông',
  'Máy hút khói',
  'Ổ cắm điện và dây nối',
  'Thiết bị an toàn',
  'Chuông cửa',
  'Công tắc',
  'Thiết bị báo động',
  'Pin',
  'Thiết bị điều khiển từ xa',
  'Chất khử mùi & làm thơm',
  'Kệ đựng',
  'Khăn mặt, khăn tắm, áo choàng tắm',
  'Ghế nhà tắm, ghế chống trượt',
  'Bồn cầu & phụ kiện',
  'Vòi sen, vòi xịt',
  'Rèm nhà tắm',
  'Các loại chăn ga',
  'Nệm',
  'Mùng/màn',
  'Gối ôm',
  'Đồ thờ cúng, phong thủy',
  'Hoa trang trí',
  'Vỏ bọc nội thất',
  'Rèm cửa, màn che',
  'Khung ảnh & vật trang trí tường',
  'Decal, tranh dán tường',
  'Đồng hồ',
  'Thảm chùi chân',
  'Thảm trải sàn',
  'Bình trang trí',
  'Nến & giá nến',
  'Gương',
  'Khăn trải bàn',
  'Đệm ngồi',
  'Miếng chặn cửa',
  'Giường',
  'Bàn',
  'Tủ quần áo',
  'Ghế',
  'Tủ bếp',
  'Kệ & giá',
  'Đồ dùng nhà bếp',
  'Dụng cụ thi công & xây dựng',
  'Dụng cụ vệ sinh nhà cửa',
  'Đèn',
  'Mắc áo',
  'Hộp đựng, giỏ đựng',
  'Kệ giày, hộp giày',
  'Móc treo',
  'Túi giặt, giỏ đựng quần áo',
  'Kệ sách',
  'Hộp đựng trang sức',
  'Hộp khăn giấy',
  'Két sắt',
  'Thiết bị chữa cháy',
  'Khóa',
  'Trang trí tiệc',
  'Chăm sóc tay',
  'Chăm sóc chân',
  'Chăm sóc móng',
  'Dầu gội ',
  'Dầu xả',
  'Thuốc nhuộm tóc',
  'Sản phẩm dưỡng tóc',
  'Sản phẩm tạo kiểu tóc',
  'Sữa rửa mặt',
  'Nước cân bằng da',
  'Kem dưỡng ẩm',
  'Dầu dưỡng ẩm',
  'Xịt khoáng',
  'Tinh chất dưỡng',
  'Tẩy tế bào chết',
  'Mặt nạ',
  'Sản phẩm dưỡng mắt',
  'Sản phẩm dưỡng môi',
  'Kem chống nắng',
  'Giấy thấm dầu',
  'Sản phẩm trị mụn',
  'Sữa tắm & chăm sóc cơ thể',
  'Chăm sóc da',
  'Sản phẩm cạo râu & hớt tóc',
  'Chăm sóc tóc',
  'Nước hoa',
  'Trang điểm mặt',
  'Trang điểm mắt',
  'Trang điểm môi',
  'Tẩy trang',
  'Dụng cụ trang điểm',
  'Dụng cụ chăm sóc da mặt',
  'Dụng cụ làm thon cơ thể',
  'Dụng cụ tẩy lông',
  'Dụng cụ chăm sóc tóc',
  'Xà phòng & Sữa tắm',
  'Mặt nạ ủ cơ thể',
  'Dầu dưỡng da',
  'Kem & sữa dưỡng thể',
  'Khử mùi cơ thể',
  'Dầu massage',
  'Chống nắng cơ thể',
  'Thực phẩm chức năng',
  'Chăm sóc cá nhân',
  'Vật dụng y tế',
  'Cây cảnh',
  'Trang trí vườn',
  'Đất trồng',
  'Phân bón & chất hỗ trợ trồng cây',
  'Hạt giống',
  'Chậu cây',
  'Dụng cụ tưới nước',
  'Dụng cụ làm vườn',
  'Dụng cụ cắt cỏ',
  'Thức ăn cún cưng',
  'Thức ăn cho mèo ',
  'Thức ăn cho thú nhỏ',
  'Thức ăn cho cá',
  'Thức ăn cho chim',
  'Thức ăn cho bò sát',
  'Bát & dụng cụ ăn',
  'Thiết bị du lịch',
  'Vòng cổ, dây dắt & rọ mõm',
  'Đồ chơi',
  'Nội thất cho thú cưng',
  'Phụ kiện thủy sinh',
  'Khay vệ sinh mèo',
  'Lót chuồng',
  'Tã thú cưng',
  'Túi & xẻng dọn vệ sinh',
  'Chăm sóc lông',
  'Chăm sóc răng miệng',
  'Quần áo & phụ kiện',
  'Vitamin & thuốc',
  'Dụng cụ thể thao & dã ngoại',
  'Giày thể thao',
  'Bộ đồ thể thao',
  'Áo thể thao',
  'Quần thể thao',
  'Áo CLB',
  'Đồ bơi',
  'Thời trang thể thao trẻ em',
  'Phụ kiện thể thao & dã ngoại',
  'Phụ kiện nội thất & trang trí',
  'Phụ kiện ngoại thất',
  'Vệ sinh oto xe máy',
  'Móc chìa khóa',
  'Tai nghe',
  'Máy nghe nhạc',
  'Micro thu âm',
  'Amply và đầu chỉnh âm',
  'Dàn âm thanh',
  'Cáp âm thanh',
  'Máy ảnh',
  'Camera giám sát',
  'Flycam',
  'Phụ kiện',
  'Phụ kiện điện thoại',
  'Phụ kiện máy tính & laptop',
  'Playstation',
  'Xbox',
  'Wii',
  'Nintendo DS',
  'Gameboy',
  'Switch',
  'PS Vita',
  'PSP',
  'PC',
  'Phụ kiện gaming & console',
  'Sách vải',
  'Sách cũ',
  'Quà tặng - giấy gói',
  'Bút bi',
  'Bút mực',
  'Bút chì',
  'Bút highlight',
  'Bút viết bảng',
  'Bảng viết & giá treo bảng',
  'Dao rọc giấy',
  'Dây & băng keo dán',
  'Hồ dán',
  'Máy in nhãn',
  'Dây đeo & thẻ tên',
  'Kẹp & ghim',
  'Máy đục lỗ',
  'Kéo',
  'Mực',
  'Lịch',
  'Dụng cụ lưu trữ giấy tờ',
  'Thước các loại',
  'Hộp bút',
  'Màu chì',
  'Màu nước',
  'Bút màu & phấn màu',
  'Sơn dầu',
  'Acrylic',
  'Cọ vẽ ',
  'Bảng màu',
  'Vải & giá vẽ',
  'Sổ vẽ',
  'Các loại giấy',
  'Sổ & ruột sổ',
  'Giấy ghi chú',
  'Tập vở',
  'Nhãn dán',
  'Đồ chơi cho bé',
  'Đồ chơi lắp ráp',
  'Búp bê & thú bông',
  'Đồ chơi nhập vai',
  'Thẻ bài & boardgame',
  'Đồ chơi ảo thuật',
  'Đồ chơi điều khiển từ xa',
  'Xe đồ chơi',
  'Đồ chơi vận động & ngoài trời',
  'Đồ chơi giáo dục',
  'Đồ chơi robot',
  'Đồ handmade',
  'Slime & nhựa dẻo',
  'Bộ quà tặng',
  'Mô hình nhân vật',
  'Tượng tĩnh',
  'Mô hình mecha/gundam',
  'Mô hình xe',
  'Bộ sưu tập truyện',
  'Tiền xu & tiền giấy',
  'Quà lưu niệm',
  'Băng - đĩa - đĩa than',
  'Album ảnh',
  'Dụng cụ may vá',
  'Đồ ăn chế biến sẵn',
  'Cơm & cháo ăn liền',
  'Lẩu tự sôi',
  'Mì ăn liền',
  'Kẹo',
  'Socola',
  'Bánh quy',
  'Bỏng ngô',
  'Khoai tây lát',
  'Rong biển sấy khô',
  'Đậu sấy khô',
  'Pudding, thạch, kẹo dẻo',
  'Thực phẩm khô',
  'Mỳ',
  'Gạo',
  'Thực phẩm đóng hộp',
  'Đồ muối',
  'Dầu ăn',
  'Gia vị & hương liệu',
  'Sốt & súp ăn liền',
  'Gói/bột gia vị',
  'Phụ gia thực phẩm',
  'Bột phủ',
  'Hương liệu',
  'Bột nở & muối nở',
  'Bột pha sẵn',
  'Bột mì',
  'Chất tạo màu',
  'Đồ trang trí',
  'Mật ong & siro',
  'Mứt',
  'Ngũ cốc',
  'Thanh dinh dưỡng',
  'Cà phê',
  'Trà',
  'Thức uống pha ',
  'Nước tăng lực',
  'Nước tinh khiết',
  'Nước trái cây',
  'Siro pha',
  'Topping',
  'Sữa các loại',
  'Sữa chua',
  'Bột kem béo',
  'Bơ các loại',
  'Phô mai & bột phô mai',
  'Kem',
  'Trứng',
  'Thực phẩm tươi sống',
  'Thực phẩm đông lạnh',
  'Các loại bánh',
];
